version: '3'
services:
  php:
    build:
      context: docker
      dockerfile: /Dockerfile
    working_dir: /app
    volumes:
      - "${CATALOG:-.}/:/app"
    ports:
      - "${HTTP_PORT:-8080}:80"
    depends_on:
      - db
    container_name: php-cv

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql-cv
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cv
    ports:
      - "3307:3306"
    volumes:
      - ./docker/cv.sql:/cv.sql

  phpmyadmin:
    container_name: pma-cv
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-front}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
volumes:
  db-data:

